config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'welcome#index'
  resources :posts
  resources :projects
  resources :contacts, only: [:new, :create]

  get '*path' => redirect('/')
end

app/models/contact.rb
class Contact < MailForm::Base
  attributes :name,  validate: true
  attributes :email, validate: /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attributes :message,  validate: true
  attributes :nickname,   captcha: true

  def headers
    {
      subject: "My Portfolio Page Contact Form",
      to: "feleck@gmail.com",
      from: %("#{name}" <#{email}>)
    }
  end
end

app/models/post.rb
class Post < ActiveRecord::Base

  extend FriendlyId
  friendly_id :title, use: :slugged
  
  def should_generate_new_friendly_id?
    slug.blank? || title_changed?
  end
end

app/models/project.rb
class Project < ActiveRecord::Base

  extend FriendlyId
  friendly_id :title, use: :slugged

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable 
  # removed: :registerable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new
    @contact = Contact.new  
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:error] = nil
    else
      flash.now[:error] = 'Cannot send message.'
      render 'new'
    end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]  
  before_action :find_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.all.order('created_at DESC').paginate(page: params[:page], per_page: 5)
  end

  def show
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post, notice: 'Post Created'
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'Post Edited'
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path, notice: 'Post Deleted'
  end

  private

  def find_post
    @post = Post.friendly.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :content, :slug)
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_project, only: [:show, :edit, :update, :destroy]

  def index
    @projects = Project.all.order('created_at DESC').paginate(page: params[:page], per_page: 5)
  end

  def show
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save(project_params)
      redirect_to projects_path, notice: "Project created"
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @project.update(project_params)
      redirect_to @project, notice: 'Project updated'
    else
      render 'edit'
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_path, notice: 'Post Deleted'
  end

  private

  def project_params
    params.require(:project).permit(:title, :description, :link, :slug)
  end

  def find_project
    @project = Project.friendly.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @posts = Post.all.limit(3).order('created_at DESC')
    @projects = Project.all.limit(3).order('created_at DESC')
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  class HTMLwithPygments < Redcarpet::Render::HTML
    def block_code(code, language)
      Pygments.highlight(code, lexer: language)
    end
  end
  
  def markdown(content)
    renderer = HTMLwithPygments.new(hard_wrap: true, filter_html: true )
    options = {
      autolink: true,
      no_intra_emphasis: true,
      disable_indented_code_blocks: true,
      fenced_code_blocks: true,
      lax_html_blocks: true,
      strikethrough: true,
      superscript: true
    }
    Redcarpet::Markdown.new(renderer, options).render(content).html_safe
  end

  def nice_date(date)
    date.strftime("%A, %b, %d")
  end
end

app/views/contacts/create.slim
h1#page_title Say Hello!
.skinny_wrapper.wrapper_padding
  h1 Thank you for your message!
  p I'll get back to you soon.

app/views/contacts/new.slim
h1#page_title Say Hello!
.skinny_wrapper.wrapper_padding
  = form_for @contact do |f|
    = f.label :name
    br/
    = f.text_field :name, required: true
    br/
    = f.label :email
    br/
    = f.email_field :email, required: true
    br/
    = f.label :message, 'Write your message here.'
    br/
    = f.text_area :message, as: :text
    br/
    .hidden
      = f.label :nickname
      = f.text_field :nickname, hint: 'Leave this field blank'
    = f.submit 'Send Message', class: 'button'

app/views/layouts/application.slim
doctype html
html
head
  title Blog
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = stylesheet_link_tag    'https://fonts.googleapis.com/css?family=Raleway:400,700'
  = stylesheet_link_tag    "https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css"
  = csrf_meta_tags

body
  header#main_navigation.clearfix
    = link_to "eMeeFe", root_path, class: "name"
    nav
      = link_to 'Articles', posts_path
      = link_to 'Projects', projects_path
      = link_to 'Contact', new_contact_path
      - if user_signed_in?
        = link_to 'Sign out', destroy_user_session_path, method: :delete
  
  - if notice 
    p.notice= notice
  - elsif alert
    p.alert= alert
  = yield

  footer#main_footer
    p.copywright 2016 &copy; eMeeFe
    nav
      = link_to 'http://twitter.com'
        i.fa.fa-twitter
      = link_to 'http://github.com/feleck'
        i.fa.fa-github
      = link_to  'http://dribbble.com'
        i.fa.fa-dribbble

app/views/posts/_disqus.slim
#disqus_thread

javascript:

    var disqus_config = function () {
        s.src = 'eMeeFe_porfolio';
        this.page.url = "#{ url_for([@post, { only_path: false }]) }";
        this.page.identifier = "#{ @post.id }" ;
        this.page.title = "#{ @post.title }" ;
    };

    (function() {  // DON'T EDIT BELOW THIS LINE
        var d = document, s = d.createElement('script');
        
        s.src = '//emeefeporfolio.disqus.com/embed.js';
        
        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
    })();

noscript Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a>

app/views/posts/_form.slim
= form_for @post do |f|
  -if @post.errors.any?
    h2
      = pluralize(@post.errors.count, 'error')
      | prevented this post from savig:
    ul
      - @post.errors.full_messages.each do |msg|
        li= msg
  = f.label :title 
  br/
  = f.text_field :title
  br/
  = f.label :content, 'Write your article here'
  br/
  = f.text_area :content
  br/
  = f.submit

app/views/posts/edit.slim
h1#page_title Edit Post
.skinny_wrapper.wrapper_padding
  = render 'form'

  = link_to 'Cancel', :back

app/views/posts/index.slim
h1#page_title Stuff I've written
#post_wrapper.skinny_wrapper
  - @posts.each do |post|
    .post
      p.date= nice_date post.created_at
      h2= link_to post.title, post
      hr

  = will_paginate @posts

app/views/posts/new.slim
h1#page_title New Post
.skinny_wrapper.wrapper_padding
  = render 'form'

  = link_to 'Cancel', posts_path

app/views/posts/show.slim
#post_show_content.skinny_wrapper.wrapper_padding
  header
    p.date= nice_date @post.created_at
    h1= @post.title
    hr
  .content
    p= markdown @post.content
  hr
  - if user_signed_in?
    #admin_links
      = link_to 'Edit Article', edit_post_path(@post)
      = link_to 'Delete Article', @post, method: :delete, data: { confirm: 'Are you sure?' }

  #share_box
    p Share The DO list
    // add twitter facebook and google plus share links
    = link_to 'http://twitter.com'
      i.fa.fa-twitter
    = link_to 'http://facebook.com'
      i.fa.fa-facebook
    = link_to  'http://plus.google.com'
      i.fa.fa-google-plus
  hr
  = render 'disqus'

app/views/projects/_form.slim
= form_for @project do |f|
  -if @project.errors.any?
    h2
      = pluralize(@project.errors.count, 'error')
      | prevented this project from savig:
    ul
      - @project.errors.full_messages.each do |msg|
        li= msg
  = f.label :title
  br/
  = f.text_field :title
  br/
  = f.label :description, "Write your project's description here"
  br/
  = f.text_area :description
  br/
  = f.label :link
  br/
  = f.text_field :link
  br/
  = f.submit

app/views/projects/edit.slim
h1#page_title Edit Project
.skinny_wrapper.wrapper_padding
  = render 'form'

  = link_to 'Cancel', :back

app/views/projects/index.slim
h1#page_title Stuff I've built
#post_wrapper.skinny_wrapper
  - @projects.each do |project|
    .post
      p.date= project.created_at.strftime("%A, %b, %d")
      h2= link_to project.title, project
      hr

  = will_paginate @projects

app/views/projects/new.slim
h1#page_title New Project
.skinny_wrapper.wrapper_padding
  = render 'form'

  = link_to 'Cancel', projects_path

app/views/projects/show.slim
#post_show_content.skinny_wrapper.wrapper_padding
  header
    p.date= nice_date @project.created_at
    h1= @project.title
    hr
  .content
    p= markdown @project.description
    .button_wrapper
      = link_to "Visit #{ @project.title }", @project.link, class: 'project_button', target: 'blank'
  hr
  - if user_signed_in?
    #admin_links
      = link_to 'Edit Project', edit_project_path(@project)
      = link_to 'Delete Project', @project, method: :delete, data: { confirm: 'Are you sure?' }

app/views/welcome/index.slim
.wrapper.wrapper_padding.clearfix
  .col-1.about.homepage_content
    h2 About
    hr/
    p Retro shabby chic cornhole tousled authentic, ethical poutine single-origin. Meh waistcoat artisan yr, banjo cred biodiesel pork belly deep v fashion axe. 90's cliche tacos blog banjo. Meditation kogi jean shorts, cred street art YOLO chicharrones tilde hella.
    p Pitchfork humblebrag jean shorts gentrify brooklyn franzen, pug chicharrones cardigan flexitarian authentic williamsburg.
      
  .col-2.homepage_content
    h2 Stuff I've Written
    hr
    - @posts.each do |post|
      h3= link_to post.title, post
      p.date= nice_date post.created_at

  .col-3.homepage_content
    h2 Stuff I've built
    hr
    - @projects.each do |project|
      h3= link_to project.title, project
      p.date= nice_date project.created_at